"""Antibiotic names used for the S1-type stewardship post-check."""

ANTIBIOTICS: tuple[str, ...] = (
    "amoxicillin",
    "amoksisilin",
    "amoxycillin",
    "ampicillin",
    "ampisilin",
    "cefadroxil",
    "sefadroksil",
    "cefixime",
    "sefiksim",
    "ceftriaxone",
    "sefriakson",
    "ciprofloxacin",
    "siprofloksasin",
    "azithromycin",
    "azitromisin",
    "erythromycin",
    "eritromisin",
    "cotrimoxazole",
    "kotrimoksazol",
    "metronidazole",
    "metronidazol",
    "penicillin",
    "penisilin",
    "antibiotik",
    "antibiotic",
    "antimikroba",
    "antimicrobial",
)
