"""Patient-facing safety-net messages.

Static, keyed by GateResult.safety_net_key. These go to the patient at intake — before any
doctor looks at the case — because the queue does not pause the illness. They are never
generated by a model: a clinician reviews this file once, and it does not drift.
"""

SAFETY_NET: dict[str, str] = {
    "emergency_now": (
        "⚠️ Gejala yang Anda sampaikan memerlukan pemeriksaan SEGERA. "
        "Mohon langsung ke IGD rumah sakit terdekat atau hubungi 119. "
        "Jangan menunggu balasan dari kami."
    ),
    "urgent_today": (
        "Gejala ini perlu diperiksa HARI INI di fasilitas kesehatan. "
        "Mohon datang ke klinik atau puskesmas terdekat hari ini. "
        "Jika memburuk (sesak, pingsan, kejang, perdarahan), langsung ke IGD atau hubungi 119."
    ),
    "clinician_review": (
        "Terima kasih. Dokter kami akan meninjau keluhan Anda dan menghubungi Anda dalam 4 jam. "
        "Jika sebelum itu muncul demam tinggi, sesak napas, nyeri hebat, atau pingsan, "
        "langsung ke IGD atau hubungi 119."
    ),
    "routine_safety_net": (
        "Terima kasih. Dokter kami akan meninjau dan membalas dalam 4 jam. "
        "Jika muncul sesak napas, nyeri dada, demam tinggi lebih dari 3 hari, atau gejala memburuk, "
        "segera ke fasilitas kesehatan terdekat."
    ),
    "wound_come_in": (
        "Luka yang tidak sembuh perlu dilihat langsung oleh dokter. "
        "Mohon datang ke klinik dalam 24 jam. Jangan mengoleskan ramuan apa pun pada luka sebelum diperiksa. "
        "Jika muncul demam, kemerahan menyebar, atau luka menghitam, datang HARI INI."
    ),
    "device_routing": (
        "Terima kasih. Kontrol alat pacu jantung harus dilakukan langsung oleh dokter jantung. "
        "Kami akan bantu jadwalkan. Sebelumnya, mohon jawab beberapa pertanyaan singkat. "
        "Jika Anda pusing berat, pingsan, atau merasakan kejutan dari alat, langsung ke IGD."
    ),
    "child_under_two": (
        "Untuk anak di bawah 2 tahun, dokter perlu memeriksa langsung. "
        "Mohon jawab beberapa pertanyaan berikut, lalu bawa anak ke fasilitas kesehatan. "
        "Jika anak tidak mau minum, kejang, atau sulit dibangunkan, langsung ke IGD."
    ),
    "mental_health_handoff": (
        "Terima kasih sudah bercerita. Kami mendengar Anda, dan Anda tidak sendirian. "
        "Seseorang dari tim kami akan menghubungi Anda sekarang. "
        "Jika Anda merasa dalam bahaya saat ini, hubungi 119 ext 8 (layanan SEJIWA) atau datang ke IGD terdekat."
    ),
}

SAFETY_NET_EN: dict[str, str] = {
    "emergency_now": (
        "⚠️ The symptoms you described require IMMEDIATE assessment. "
        "Please go directly to the nearest hospital emergency department or call 119. "
        "Do not wait for our reply."
    ),
    "urgent_today": (
        "These symptoms need assessment at a healthcare facility TODAY. "
        "Please visit the nearest clinic or community health centre today. "
        "If symptoms worsen (breathing difficulty, fainting, seizure, or bleeding), "
        "go directly to the emergency department or call 119."
    ),
    "clinician_review": (
        "Thank you. Our doctor will review your symptoms and contact you within four hours. "
        "If you develop a high fever, breathing difficulty, severe pain, or fainting before then, "
        "go directly to the emergency department or call 119."
    ),
    "routine_safety_net": (
        "Thank you. Our doctor will review your case and reply within four hours. "
        "If you develop breathing difficulty, chest pain, a high fever lasting more than "
        "three days, or worsening symptoms, seek care at the nearest healthcare facility."
    ),
    "wound_come_in": (
        "A wound that is not healing needs to be examined by a doctor. "
        "Please come to the clinic within 24 hours. Do not apply any remedies before examination. "
        "If fever develops, redness spreads, or the wound turns black, seek care TODAY."
    ),
    "device_routing": (
        "Thank you. A pacemaker check must be performed in person by a cardiologist. "
        "We will help arrange it. First, please answer a few short questions. "
        "If you have severe dizziness, faint, or feel a shock from the device, go directly to emergency care."
    ),
    "child_under_two": (
        "Children under two need an in-person examination. "
        "Please answer the following questions, then take the child to a healthcare facility. "
        "If the child cannot drink, has a seizure, or is difficult to wake, go directly to emergency care."
    ),
    "mental_health_handoff": (
        "Thank you for telling us. We hear you, and you are not alone. "
        "A member of our team will contact you now. If you feel you are in immediate danger, "
        "call 119 extension 8 (SEJIWA) or go to the nearest emergency department."
    ),
}


def message_for(key: str, language: str = "id") -> str:
    messages = SAFETY_NET_EN if language == "en" else SAFETY_NET
    return messages.get(key, messages["clinician_review"])
